#%RAML 0.8
title: Model

/resource-a:
  displayName: Resource A
  get:
    displayName: Resource A GET
  post:
    displayName: Resource A POST

  /sub-resource-b:
    displayName: Sub-resource AB
    get:
      displayName: Sub-resource AB GET

  /sub-resource-c:
    displayName: Sub-resource AC
    get:
      displayName: Sub-resource AC GET

/resource-d:
  displayName: Resource D
  get:
    displayName: Resource D GET
  post:
    displayName: Resource D POST