AS Log Monitor
==============

 

AS Log Monitor is a time-based monitor that collects log entries from
the AS Logs on the JBOSS nodes.

The monitor fetches log locations and patterns for the JBOSS nodes
available in DataHandler.getHosts() and monitors the logs

The monitor adds all the retrieved log entries to the cache, to be
accessed centrally.

 

*Monitor Configuatration*

Property

Accepted Values

Default Value

Description

Example

monitor.aslogmon.enabled

true|false|1|0

false

Property to enable of disable the monitor before run

monitor.aslogmon.enabled=true

monitor.aslogmon.collectionTime

numbers

5

Property to specify the interval in seconds between collections of log
entries

monitor.aslogmon.collectionTime=

5

monitor.aslogmon.checkInterval

numbers

100

Property to specify the intervals to check for entry until entry is
found or timeout is reached

monitor.aslogmon.checkInterval=100

monitor.aslogmon.defaultTimeout

numbers

120000

Property to specify the timeout for getEntry method

monitor.aslogmon.defaultTimeout=

120000

monitor.aslogmon.minWaitTime

numbers

100

Property to specify the minimum time to wait for response from
monitoring agent

monitor.aslogmon.minWaitTime=

100

 

*Retrieving Log Entries gathered by the Monitor*

The Log Monitors provide 2 methods for retrieving log entries that have
been gathered and placed in the cache.

In order to call these methods you must first retrieve the instantiated
monitor.

[source,groovy]
----
def thismon = AbstractMonitorHelper.getMonitors().find{ it.name == aslogmon }
---

_getEntry(String filter) -_This method returns the first log entry
containing the filter, that is gathered after the method is called.

[source,java]
----
LogEntry logEntry = thismon.getEntry(filter);
----

getAllEntries(String filter) - This method returns all log entries that
are currently stored in the cache for this monitor and containing the
filter that is passed in.

[source,java]
----
List<LogEntry> logEntries = thismon.getAllEntries(filter);
----
