#%RAML 0.8
---
title: Resource Pattern is invalid

/CAPITAL-LETTERS:
  get:
    responses:
      200:

/has-digit-1:
  get:
    responses:
      200:

/has_non_dash_symbols:
  get:
    responses:
      200: